FROM python:3.11-slim

# FFmpeg install
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Python dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Project files
COPY . .

# Render will provide PORT
EXPOSE 10000

# Start backend
CMD ["python", "backend.py"]